### ISSUE TITLE
windows10运行compile脚本不报错，也不生成任何编译后的pdf文件

### ISSUE THREAD

**Issue by zmrenwu** [shifujun/UESTCthesis#110]
之前一直是没有问题的，也顺利地提交了论文预审，但最近更新了win10操作系统到最新版本，运行编译脚本后不报错，也不生成任何编译后的pdf文件了，感觉天要塌了。希望大家救救我。下面是生成的log文件：
[thesis.log](https://github.com/shifujun/UESTCthesis/files/1950513/thesis.log)

**Comment by Mrneet** [comment]
我三台电脑，一台中文最新系统+texlive，没毛病；另一台英文最新系统+texlive，同样的问题；还有一台中文最新系统+MiTeX，一样的问题。

**Comment by zmrenwu** [comment]
解决了，解决方案就是重装latex
