### ISSUE TITLE
wiki 中的  lshort-zh-cn.pdf 链接已失效

### ISSUE THREAD

**Issue by lyh543** [shifujun/UESTCthesis#122]

**Comment by lyh543** [comment]
[TeX环境安装](http://bbs.ctex.org/forum.php?mod=viewthread&tid=48244&page=1#pid337079)也失效了。

**Comment by H-Li24** [comment]
百度云链接已经失效了，请问是否可以重新上传？

**Comment by H-Li24** [comment]
因为这本书是盗版的，资源被百度云删除了。
如果需要的话，搜索文件名，csdn能下载。

**Comment by note286** [comment]
lshort-zh-cn地址已更新。

**Comment by Clyedhol** [comment]
这是来自GPS的邮箱。感谢你的来信。
