### ISSUE TITLE
对于中英文混排，是不是需要加~更美观呢？

### ISSUE THREAD

**Issue by lxhm** [shifujun/UESTCthesis#13]
例如：电子科技大学的英文是~uestc。

这样吗？怎样做最简便，最美观呢？谢谢:)

**Comment by andnot** [comment]
@allecs 同学你是全手动加~吗？这个工作量好大啊……

@shifujun 其实很多从CTeX转过来的同学也希望模板可以有中英文自动加间隔的功能吧，哪怕功能有限制，作为一个选项出现也可以。谢谢！

**Comment by allecs** [comment]
@andnot 写个python脚本就可以了，也算半手动吧，当然最好的还是模版提供功能

**Comment by andnot** [comment]
@allecs 可惜不会python啊……
嗯是啊，模板本身要是能提供这个功能就好了。
