### ISSUE TITLE
关于插入eps图像

### ISSUE THREAD

**Issue by lxhm** [shifujun/UESTCthesis#15]
eps图像怎么插入呢，试过用插入图像的方法，编译提示未知图像格式 .eps，非常感谢耐心解答，祝好。

**Comment by andnot** [comment]
@shifujun epstopdf宏包可以解决这个问题，很方便的。参见[这里](https://www.ctan.org/pkg/epstopdf)，还有[这里](http://blog.sciencenet.cn/blog-111625-521363.html)。

**Comment by shifujun** [comment]
@andnot 那个宏包应该也是内部转换了格式吧。pdflatex不支持eps格式是编译器决定的。如果那个宏包可以直接插入eps文件，你实验过很好使的话，你可以把使用方法写在Wiki里。

**Comment by andnot** [comment]
@shifujun 对，这个宏包本质上就是把eps转换为pdf格式的图片了。
不过用它有个好处，就是代码复用性增强了。比如之前用户的文档都是直接插入eps，则TeX代码中的图片后缀都是.eps。现在若想将之前的TeX代码复制过来，又不愿一个个修改源代码中的文件后缀，则可以直接在导言区加上epstopdf包，简单快捷。
