### ISSUE TITLE
clean.sh脚本里需要删除*.glsdefs文件

### ISSUE THREAD

**Issue by OnceMore2020** [shifujun/UESTCthesis#31]
若不删除`*.glsdefs`文件，更改符号表之后再次编译并不会覆盖之前的定义，需要每次编译前删除掉`thesis.glsdefs`文件即可实现更新后的符号表示覆盖之前的符号表。建议在clean.sh脚本中添加一行来删除。

**Comment by shifujun** [comment]
fix by v1.1.0.
