### ISSUE TITLE
A Bug report and solution

### ISSUE THREAD

**Issue by YongjieLuo** [shifujun/UESTCthesis#34]
你好，
在老旧的windows xp上首次编译失败，无法生成thesis.pdf文件，
检查日志thesis.log中的error：
-------------------------------------------------------------------------------
<C:/WINDOWS/Fonts/simsun.ttc><C:/WINDOWS/Fonts/simsun.ttc><C:/WINDOWS/Fonts/s
imhei.ttf><C:/WINDOWS/Fonts/simhei.ttf><C:/WINDOWS/Fonts/simhei.ttf><C:/WINDOWS
/Fonts/simhei.ttf>
!pdfTeX error: pdflatex (file umvs): Font umvs at 723 not found
 ==> Fatal error occurred, no output PDF file produced!
-------------------------------------------------------------------------------

根据 https://dev-eth0.de/miktex-makepk-pk-font-umvs-could-not-be-created/
原因是MikTeX的字体映射文件找不到umvs字体，
所以解决办法是重建字体映射文件。

打开windows的命令行窗口，进入MikTeX安装目录中的bin目录，例如：
C:\Program Files\MiKTeX 2.9\miktex\bin

运行命令：
initexmf --mkmaps
initexmf --update-fndb

然后重新进入UESTCthesis-master\example目录，
编译即可。

**Comment by shifujun** [comment]
你好。我几个问题：

1，你所说的老旧的xp是哪个版本？我在xp sp3上是试验过从安装到编译的，没有问题。

2，你用的miktex是什么版本？也是旧的吗？字体映射这两个命令（步骤）在miktex安装时应该就执行过。

3，这个问题算是我这个模板的Bug嘛？如果在你所说的老旧的xp版本上，按照模板的wiki中的tex环境安装步骤安装后依然会出现你所说的问题，那我们应该把这个问题写在wiki里。

**Comment by BinLee** [comment]
学院最近给出了新的模板，说了改了标题之间间距，不知道模板中是否有更新？
http://www.ss.uestc.edu.cn/index.php/yanjiushengjiaoxue/2015/03-11/1184.html

**Comment by shifujun** [comment]
@BinLee 你给出的链接是信软学院的通知，而研究生院没有新的关于撰写规范的通知。研究生博士生是研究生院统一管理的，我相信研究生院如果没有新的通知，各学院无权也不会更改格式规范的。

模板参考的是http://gr.uestc.edu.cn/article.shtml?id=6643 通知的规范。你可以自己对比一下。如果有不一样的地方可以告诉我。

**Comment by BinLee** [comment]
谢谢回复，对比了一下，要求没有区别，谢谢!
