### ISSUE TITLE
中文摘要关键词少于5个时编译无法通过格式不正确

### ISSUE THREAD

**Issue by Chenhuajie** [shifujun/UESTCthesis#35]
中文摘要定义的关键词如果少于5个会出现编译错误；英文关键词若少于5个可以编译通过，但摘要首字符消失且其成为第5个关键词。

PS：我记得规范中要求的关键词数目不是硬性要求5个的，我这里用的是4个。

**Comment by Chenhuajie** [comment]
另外求要如何把主要符号表和略缩词表的空页去掉，我没有用到这两个东西啊。。。（用的本科模板）

**Comment by shifujun** [comment]
｛｝是LaTeX的必选参数，只能空置不能取消。

**Comment by Chenhuajie** [comment]
那么那个主要符号表和略缩词表呢？如何去掉？

**Comment by shifujun** [comment]
看wiki。不使用就不会生成。只能是因为你写错了什么东西。
