### ISSUE TITLE
关于摘要的页码问题

### ISSUE THREAD

**Issue by rectaflex** [shifujun/UESTCthesis#36]
今天去文印中心打论文，被指出一个问题。就是假设中文和英文摘要都是1页，那么模板会把英文摘要的页码标记成罗马字符3，但应该是2。学校给的文件里也有说明：“
（1）中文摘要、英文摘要、目录等前置部分用罗马数字连续编排。
（2）中文摘要、英文摘要和目录，每部分采用双面印制，即正面和背面连续编排页码。若某一部分的页数为奇数时，该部分的最后一页单面印制，即该页的背面页为空白，不编页码和页眉。“

而且学校给的模板的编排也是2，请问这个问题可以解决么？

**Comment by shifujun** [comment]
https://github.com/shifujun/UESTCthesis/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%AD%A3%E6%96%87%E4%B9%8B%E5%89%8D%E5%AD%98%E5%9C%A8%E7%A9%BA%E7%99%BD%E9%A1%B5%EF%BC%8C%E9%A1%B5%E7%A0%81%E4%B8%8D%E8%BF%9E%E7%BB%AD%EF%BC%9F
