### ISSUE TITLE
1.1.2中未引用的文献依然会在参考文献中显示的问题

### ISSUE THREAD

**Issue by rectaflex** [shifujun/UESTCthesis#37]
因为我的所有文献都用软件管理，所以bib中有很多没有被引用的条目。在之前用1.1.1的时候这些没有被引用的条目不会显示在参考文献中。更新到1.1.2后发现所有的条目（不管有没有被引用）都显示在参考文献中了，请问该如何解决？

**Comment by shifujun** [comment]
https://github.com/shifujun/UESTCthesis/wiki/%E5%BD%95%E5%85%A5%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%92%8C%E7%A0%94%E7%A9%B6%E6%88%90%E6%9E%9C#%E6%9C%AA%E5%BC%95%E7%94%A8%E7%9A%84%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE
