### ISSUE TITLE
右上角角标为问号

### ISSUE THREAD

**Issue by kingname** [shifujun/UESTCthesis#40]
我运行complie.bat以后，生成的thesis.pdf打开发现右上角有角标的地方显示的是问号。
![如图](http://7sbpmp.com1.z0.glb.clouddn.com/1.png)
请问这是编码问题还是什么问题？如何解决？谢谢。

**Comment by shifujun** [comment]
这只是因为后来的更新将测试用的参考文献都删除了，当bibtex在bib里找不到引用的标签时，就会显示问号。

总之可以确定这方面没有bug的。
