### ISSUE TITLE
参考文献 @inprocedings 不显示 booktitle的内容

### ISSUE THREAD

**Issue by wuduande** [shifujun/UESTCthesis#41]
@inproceedings{tan2010future,
  AUTHOR =       {Fourney, M E},
  TITLE =        {Advances in holographic photoelasticity},
  BOOKTITLE =    {Applied Mechanics Division. Symposium on Applications of Holography in Mechanics，August 23-25，1971. University of Southern California，Los Angeles, California},
  YEAR =         {1971},
  miscYEAR =     {c1971},
  editor =       "{American Society of Mechanical Engineers}",
  normaleditor = "{American Society of Mechanical Engineers}",
  volume =       {},
  number =       {},
  series =       {},
  pages =        {17-38},
  address =      {New York},
  month =        {},
  organization = {},
  publisher =    {ASME},
  note =         {},
  abstract =     {},
  keywords =     {},
  TypeofLit =    {C},
}

仅显示：
[1] M. E. Fourney. Advances in holographic photoelasticity[C]. New York: ASME, 1971, 17–38

**Comment by livey** [comment]
遇到了同样的问题。 改成conference 试试？

**Comment by wuduande** [comment]
嗯，发布了issue才看到新发布的@conference。不过，修复@inprocedings问题是必要的。因为google scholar给出的一半结果都是采用@inprocedings的格式。如果全部需要作者自己转换格式，工作量是较大的。修复之后，作者可以完全不关心参考文献的问题。

**Comment by wuduande** [comment]
经验证，@conference的问题：当不输入address字段时，publisher字段不显示。而google scholar提供的bibtex没的address字段。

**Comment by shifujun** [comment]
如果你认为你的bibtex里的inprocedings格式实际上和模板定义的conference是完全一样的。你可以在bst里搜索`FUNCTION {book}`（这里是FUNCTION {conference}之后），在这一行之前加入一行`FUNCTION {inproceedings}{conference}`。

然而我说如果呢，是因为这是不大可能完全一样的。模板的参考文献类型之所以改成这个样子，完全是因为学校给出的规范毫无规范可言。大家又特别重视和学校的范例格式完全一致。所以呢，模板就成这样了。现在这种情形呢，你不大可能从Google或者其他参考文献库导出直接能用的条目。实际上，就算用国标，Google直接导出的条目也大多是缺失字段的。如果缺失字段，你输出的参考文献条目就不可能和范例一致。

总之，想要和学校的范例输出效果一致，你需要选择正确的参考文献类型，确认和范例的bib文件中各种类型的例子的字段完全一致，不能缺少字段。像你说出的，不输入address字段时，publisher就不显示。这确实是不够好，但你不输入address，我即使把publisher显示出来，它也是和范例不符的。

**Comment by wuduande** [comment]
哇，回复这么快。感谢作者！
其实问题是这样的，学生并不关心格式的细节。而是关心格式大概看起来与规范不要差太远。因为为了达到标准格式，要去查到会议的地点是非常困难的，尤其是会议已经过去太久这种情况。今天为了查地址查了2个小时。而会议地点这种信息本身不太重要。相比而言publisher更重要一些。
所以，如果作者认为参考文献必须所有字段齐全，那么完全可以在生成的pdf参考文献处输出错误信息。因为要发现这个address的问题需要反复编译非常多次。
最后，谢谢作者啦，论文省了很多事！~
