### ISSUE TITLE
本科生毕业论文用英文写作时，学位信息会出现问题

### ISSUE THREAD

**Issue by NeonAsuka** [shifujun/UESTCthesis#42]
thesis.tex文件中如出现
“\documentclass[bachelor,english]{uestcthesis}”编译会出现问题。
但如果改为
“\documentclass[doctor,english]{uestcthesis}”则可以顺利通过。但论文偶数页页眉的信息会有问题。

在此请教解决方案

**Comment by shifujun** [comment]
v1.2.3已经解决了。
