### ISSUE TITLE
Bug提交以及建议 by Think小黑 on May 31st 2015

### ISSUE THREAD

**Issue by 02015678** [shifujun/UESTCthesis#44]
1、论文模板经过很多次的改动后容易出现不同步的情况。例如使用说明中还有titlepage.tex，但现在版本的已经没有封面了。例如现在版本的摘要中引用的参考文献在reference.bib文件中没有，导致出来的引用显示为问号。

2、请在首页写清楚，因为ctex更新改动太大，模板不能同时兼容新旧ctex，使用旧版本ctex的(包括使用TexLive 2014的，或者使用CTEX/Miktex已经有ctex宏包，且在2015年05月25日后没有更新过的)请使用1.2.2版本。使用新ctex宏包的(包括在2015年05月25日后安装Miktex的，以及在此日期后更新CTEX/Miktex的)，请使用1.2.3版本。

3、请修改compile.bat，将所有的 .\ 修改为 ./ 。因为 .\ 不兼容TexLive版的Binary。Windows系统命令提示符是认得 ./ 的，这个请放心。

**Comment by shifujun** [comment]
问题1，已经修复了。
问题2，版本的事对小白用户太麻烦。总要求用户用最新版可能好维护一点。
问题3，我现在没有方便的Windows环境了。这个周末没时间验证这个问题，继续拖着吧。
