### ISSUE TITLE
章节下的第一段开头没有4个半角空格缩进。

### ISSUE THREAD

**Issue by zengcyoung** [shifujun/UESTCthesis#45]
1.2.3版本的章节下如果直接起段落而不起小节，则章节下的第一段不会缩进4个半角空格字符。如下，
```
\chapter{示例章节}
示例段落。

示例第二段。
```

则“示例段落”不会被4个半角空格字符缩进。

**Comment by zengcyoung** [comment]
据说使用了`ctex`包中文第一段都会自动缩进，所以难道是新版`ctex`的问题么。加了一个`indentfirst`包解决了。
在`cls`文件加入
```
\RequirePackage{indentfirst}
```
即可。

**Comment by shifujun** [comment]
1.2.6版本固定了依赖宏包的版本。应该不会有这个问题了。
