### ISSUE TITLE
"\endinput" should be removed from the file of uestcthesis.bst.

### ISSUE THREAD

**Issue by shouxi** [shifujun/UESTCthesis#48]
I suggest removing `\endinput` from the bst file. Otherwise, it may cause this Error 
> "\" can't start a style-file command---line 5273 of file uestcthesis.bst
 : 
 : \endinput

**Comment by shifujun** [comment]
uestcthesis.bst文件只有2640行。你贴的log上显示的5273行很奇怪。

\endinput命令不是我写的。它是从dtx中生成bst文件时由ins文件的机制自动加上的。这个命令应该不会产生任何问题。它在每个由ins文件导出的文件结尾都存在。

另外你贴的这个错误信息会暂停编译吗？
