### ISSUE TITLE
自定义缩略词格式时出现编码无法识别

### ISSUE THREAD

**Issue by Qrox** [shifujun/UESTCthesis#49]
学长好，

我想在正文中用`中文名称 (English full name, acronym)`的形式作为第一次显示缩略词的格式，于是我参照glossaries宏包的文档添加了以下指令

    \glsaddstoragekey{cn}{}{\glsentrycn}
    \defglsentryfmt[\acronymtype]
        {\ifglsused{\glslabel}
            {\glsentryshort{\glslabel}}
            {\ifglshasfield{cn}{\glslabel}
                {\glsentrycn{\glslabel}~(\glsentrylong{\glslabel},~\glsentryshort{\glslabel})}
                {\glsentrylong{\glslabel}~(\glsentryshort{\glslabel})}}}
    
    ...
    
    \newacronym[description=电池管理系统, cn=电池管理系统]{bms}{BMS}{battery management system}
    
    ...
    
    \gls{bms}

然而当执行到`\gls{bms}`时，编译器报错

    ! Package inputenc Error: Unicode char 电 (U+7535)
    (inputenc)                not set up for use with LaTeX.

文中其余部分的中文都能被正确识别。把`cn=电池管理系统`替换成`cn=test`之后便成功编译。
我第一次用LaTeX，对其不太熟悉，请问这是什么原因导致的，怎样解决？谢谢！

**Comment by shifujun** [comment]
看你的描述，你可能没看过wiki。
https://github.com/shifujun/UESTCthesis/wiki/使用主要符号表和缩略词表#修改缩略词第一次引用的显示格式

如果参照wiki还有问题，再具体说。

**Comment by Qrox** [comment]
谢谢，之前没有注意到维基，抱歉。用维基里面的方法的确可行，不过用`##1`代表标签则中文名称、英文名称和缩略词都不显示，使用`\glslabel`才显示。但是如果想要自定义其他中文字段，用维基里的方法仍然会导致编码无法识别。不过目前来说维基里的方法已经够用了。
