### ISSUE TITLE
论文页眉页脚边距不符合要求，目录行间距取固定值20磅等问题

### ISSUE THREAD

**Issue by uestcbraid** [shifujun/UESTCthesis#51]
今天形式审查告诉我有以下问题：
1、页眉边距20mm，页脚边距20mm
2、目录行间距取固定值20磅

**Comment by WoodyBuendia** [comment]
请检查你打印设置，很多pdf默认的打印首选项调整页面大小为：适合；这样打印出来的页眉页脚会变。
如图：

请在打印店打印是务必选择“实际大小”

2016-04-18 

tinywoody 



发件人：Likai <notifications@github.com>
发送时间：2016-04-18 18:29
主题：[shifujun/UESTCthesis] 论文页眉页脚边距不符合要求，目录行间距取固定值20磅等问题 (#51)
收件人："shifujun/UESTCthesis"<UESTCthesis@noreply.github.com>
抄送：

今天形式审查告诉我有以下问题：
1、页眉边距20mm，页脚边距20mm
2、目录行间距取固定值20磅
