### ISSUE TITLE
沙河模板使用形式审查几点问题

### ISSUE THREAD

**Issue by uestcbraid** [shifujun/UESTCthesis#53]
以下是形式审查老师给的意见：
1、摘要800字内
2、页眉、章序与章名之间空一个半角字符
3、图序与图名直接空一个半角字符
4、公式字体不是Times New Roman

最后一个公式字体的问题貌似学校没有要求，不知道形审老师是什么意思，摘要800字以内让我无力吐槽，沙河无解了

**Comment by shifujun** [comment]
这4点都不成立。建议向研究生院学位科反映问题。

**Comment by WoodyBuendia** [comment]
你是物电的么？今天上午看到一份形审结果说摘要800字内。

对于第四点，我们的论文送审均被要求公式中字体为Times New Roman.

2016-04-22 

tinywoody 



发件人：Likai <notifications@github.com>
发送时间：2016-04-22 14:55
主题：[shifujun/UESTCthesis] 沙河模板使用形式审查几点问题 (#53)
收件人："shifujun/UESTCthesis"<UESTCthesis@noreply.github.com>
抄送：

以下是形式审查老师给的意见：
1、摘要800字内
2、页眉、章序与章名之间空一个半角字符
3、图序与图名直接空一个半角字符
4、公式字体不是Times New Roman
最后一个公式字体的问题貌似学校没有要求，不知道形审老师是什么意思，摘要800字以内让我无力吐槽，沙河无解了

**Comment by shifujun** [comment]
我软件学院的，已经上班了。

第4点是受研究生院学位科支持的。没有任何学术文章会要求用Times字体。我们原则上是按主流字体，实际上是采用和ACM论文一样的字体。

形审的老师可能不怎么读国际论文。

**Comment by uestcbraid** [comment]
我尝试改了一下cls，使用\ \ 代替~就可以达到2要求的效果，这是啥意思，word默认的是两个半角空格？还有就是我想问一下师兄怎么学习编写模板，有没有资料推荐，网上搜不到模板写的教程

**Comment by obserthinker** [comment]
同想知道怎么学习编写模板~
