### ISSUE TITLE
论文格式链接失效

### ISSUE THREAD

**Issue by EmilySunieee** [shifujun/UESTCthesis#55]
这里有一个2015年的毕设论文格式，和我们2016年核对了一下是一样的，但是找不到2014年的了，应该都差不多吧，附件附上
[电子科大2015本科毕业设计管理办法.pdf](https://github.com/shifujun/UESTCthesis/files/243912/2015.pdf)

**Comment by tatowilson** [comment]
附件是2016届的本科毕业设计（论文）管理办法（2015年修订版）。
[电子科技大学本科毕业设计（论文）管理办法（2015年修订版）.pdf](https://github.com/shifujun/UESTCthesis/files/327006/2015.pdf)

**Comment by tatowilson** [comment]
2016毕设相关文件传送门：
[毕业设计相关表格2016](http://www.jwc.uestc.edu.cn/news/read.do?nid=1848)

其中的范例文件附件附上
[0.电子科技大学本科毕业论文撰写范例.zip](https://github.com/shifujun/UESTCthesis/files/327022/0.zip)
