### ISSUE TITLE
使用eqarray环境中，最后一个公式的编号不能和其它的右对齐

### ISSUE THREAD

**Issue by obserthinker** [shifujun/UESTCthesis#57]
equation环境，编号都是右对齐的. eqarray环境，公式在等号处对齐，但是公式编号没有对齐。

代码如下：
```
\begin{eqnarray}
\nabla\times\mathbf{\mathit{H}}&=&\frac{\partial \mathbb{\mathit{D}}}{\partial t}+\mathbf{\mathit{J}}\\
\nabla\times\mathbf{\mathit{E}}&=&-\frac{\partial \mathbb{\mathit{B}}}{\partial t}-\mathbf{\mathit{J}}_m
\end{eqnarray}
```

**Comment by obserthinker** [comment]
图片在此，刚才硬是上传不成
![capture](https://cloud.githubusercontent.com/assets/10296215/15203135/4e115eaa-1833-11e6-95d5-27f81de9ccf5.PNG)

**Comment by obserthinker** [comment]
图片在此，刚才硬是上传不成。头两个是equation环境，公式编号右对齐，后两个是eqarray环境，公式在等号处对齐，公式编号不能对齐。三行公式的时候，也是最后一个公式编号不会对齐。
![capture](https://cloud.githubusercontent.com/assets/10296215/15203157/8815c262-1833-11e6-8471-204757dd9359.PNG)

**Comment by shifujun** [comment]
确认有这个问题。原因可能不太好查。我会找时间看的。建议先用acrobat编辑pdf。

**Comment by obserthinker** [comment]
好的，谢谢。
shifujun <notifications@github.com>于2016年5月12日 周四下午12:21写道：

**Comment by shifujun** [comment]
今天晚上花了些时间解决了这个问题。这个问题的原因是hyperref宏包（pdf超链接宏包）对eqnarray的结束进行了hook。通过将|\endeqnarray|命令还原回原本的定义修复了该问题。

修复后测试了一下对eqnarray里最后一个公式添加label后依然能正常引用，使用超链接。所以我没有读懂hyperref的hook到底起什么作用。对于论文模板来说打印效果是第一位的，超级链接只是辅助功能，由于时间的关系，我就不深究这个改动会有什么问题了。

**Comment by obserthinker** [comment]
非常感谢！多谢学长能抽空维护这个repository。

shifujun <notifications@github.com>于2016年6月5日周日 上午12:05写道：

**Comment by andnot** [comment]
载入 ams math 包后，用 align 环境输入多行公式会不会好一些？

**Comment by andnot** [comment]
顺手测试了一下，没有问题：
<img width="442" alt="2016-06-14_101147" src="https://cloud.githubusercontent.com/assets/6057231/16029131/dad5c674-3218-11e6-8cbb-5a4758ca0878.png">


```latex
\begin{align}
	\nabla\times\mathbf{\mathit{H}}&=&\frac{\partial \mathbb{\mathit{D}}}{\partial t}+\mathbf{\mathit{J}}\\
	\nabla\times\mathbf{\mathit{E}}&=&-\frac{\partial \mathbb{\mathit{B}}}{\partial t}-\mathbf{\mathit{J}}_m
\end{align}
```
