### ISSUE TITLE
如何使得公式字体和公式编号字体不一样

### ISSUE THREAD

**Issue by letou662012** [shifujun/UESTCthesis#58]
根据我们学院的奇葩规定，公式编号字体要5号，请问一下怎么样修改可以，尝试用\def\maketag@@@#1{\hbox{\m@th\normalfont\huge#1}}这个命令以
(1)方式：\makeatletter
\def\maketag@@@#1{\hbox{\m@th\normalfont\huge#1}}
\makeatother
(2)方式以\begingroup方式加入公式内

两种方式都不可信，而随便建一个新的文档，用这种方法确实能够使得公式字体和公式编号字体不一样

请问下应该如何修改

**Comment by letou662012** [comment]
已解决

**Comment by shifujun** [comment]
@letou662012 建议将解决方法添加到wiki中，方便你们学院的其他同学。
