### ISSUE TITLE
英文选项下，正文中图标标题仍未中文

### ISSUE THREAD

**Issue by obserthinker** [shifujun/UESTCthesis#59]
使用英文选项的话，会出现页眉缺失，通过手动添加usetcthesis.cls中

`\newcommand{\thesisname@english}{Bachelor Thesis of University of Electronic Science and Technology of China}%为bachelor选项下使用english选项而设。`

中大括号内内容得到修正。但是图标标题如何改为英文？

**Comment by shifujun** [comment]
这两个预定名分别是
\renewcommand{\CTEX@figurename}{Figure}
\renewcommand{\CTEX@tablename}{Table}

我比较忙，对源码也生疏了点，如果可以的话，你先试着自己找到位置添加吧。

**Comment by shifujun** [comment]
另外，英文选项是给留学生准备的，所以设计上没考虑和bachelor选项共用。

**Comment by obserthinker** [comment]
多谢，我尝试一下。

**Comment by obserthinker** [comment]
之前你所述的两个预定名已在排版源代码中，无需添加。

查看ctex手册，修改图表题名需要首先对题名进行初始化定义，这一步骤在排版源代码中已有。然后需要修改原始的标题定义，代码为
```tex
\renewcommand*\figurename{\CTEX@figurename}
\renewcommand*\figurename{\CTEX@figurename}
```

由于不熟悉latex，我将cls文件中所有的`\renewcommand{\CTEX@figurename}{Figure}`更换为了上述代码，结果显示图标名称变为中文。

希望能有所帮助。

**Comment by MrWanter** [comment]
@obserthinker 同学求助
没搞明白是怎么替换的，我是这样修改的，但是还是没有效果，出来还是‘图’而不是'Figure'
```
\newpage
\phantomsection
\addcontentsline{toc}{chapter}{Foreign Language Materials}

\renewcommand{\CTEX@figurename}{Figure}
\renewcommand{\CTEX@tablename}{Table}

\include{contents/original}
\newpage
\phantomsection
\addcontentsline{toc}{chapter}{Translations of Foreign Language Materials}
\renewcommand{\chaptermark}[1]{\markboth{Translations of Foreign Language Materials}{}}
\def\leftmark{Translations of Foreign Language Materials}

\renewcommand{\CTEX@figurename}{Figure}
\renewcommand{\CTEX@tablename}{Table}

\setcounter{chapter}{0}
q
\include{contents/translation}
请问你是怎么处理的呢，谢谢！

**Comment by obserthinker** [comment]
@MrWanter 
可以将你的代码中
```
\renewcommand{\CTEX@figurename}{Figure}
\renewcommand{\CTEX@tablename}{Table}
```
这两行改为
```
\renewcommand*\figurename{\CTEX@figurename}
\renewcommand*\figurename{\CTEX@figurename}
```
试试。如果还不行的话可以加我QQ讨论一下，把我的cls文件给你看看。
