### ISSUE TITLE
章标题段前段后30磅和word不一致

### ISSUE THREAD

**Issue by EmilySunieee** [shifujun/UESTCthesis#61]
章标题的段前段后要求是30磅，我们latex模
![default](https://cloud.githubusercontent.com/assets/18757595/16183818/bfeb31bc-36e8-11e6-9e38-13a3ded329a2.png)
板和word不一致，肉眼可见的差距，求学长的指标！

**Comment by shifujun** [comment]
1，请不要用肉眼作为标准。
2，请不要用Word作为标准。

**Comment by EmilySunieee** [comment]
学长霸气！好的，谢谢学长！

**Comment by EmilySunieee** [comment]
唉，我们学院变态的连目录的点数都要按照word来我也是醉了，学长能不能指导一下在哪里可以修改一下段前段后，要不论文还得打回来重写，唉，受不了学院了

**Comment by shifujun** [comment]
本科的章标题段前间距在这行：
https://github.com/shifujun/UESTCthesis/blob/master/source/uestcthesis.dtx#L1053

如果你改好了，建议你在wiki里记录一下。

**Comment by EmilySunieee** [comment]
好的！
