### ISSUE TITLE
BibTeX 中的inproceedings条目，booktitle无法显示。

### ISSUE THREAD

**Issue by yiranjianning** [shifujun/UESTCthesis#62]
inproceedings条目为会议论文集中的一篇文章。不可少域author, title, booktitle, year.对于booktitle，生成的pdf中无法出现booktitle部分。无论是学学士还是硕士都不行。

**Comment by shifujun** [comment]
模板定义的参考文献类型中没有inproceedings。你应该是没仔细看过wiki。
