### ISSUE TITLE
BibTeX 中的inproceedings条目，booktitle无法显示。

### ISSUE THREAD

**Issue by yiranjianning** [shifujun/UESTCthesis#63]
尝试了学士和硕士模板，都无法显示inproceedings条目中的必须保留的字段booktitle内容。临时的办法是将booktitle改为publisher，虽然这样改动之后，该inproceedings就缺少booktitle，但编译脚本竟不提示错误，仍能编译出符合预期的参考文献样式。

**Comment by shifujun** [comment]
我哪里写了inproceedings条目了？哪里又写了“必须保留的字段booktitle”？

**Comment by yiranjianning** [comment]
用bibtex作为参考文献库的话，引用专利就是inproceedings条目啊。bibtex规范要求inproceedings的保留字段有booktitle.http://blog.sina.com.cn/s/blog_4cf1445d0100yfrb.html

**Comment by shifujun** [comment]
你用新浪博客作为规范，而不看模板的Wiki。就不用提Issue给模板了。

**Comment by yiranjianning** [comment]
或者看如下维基百科的截图：
![bbbbbbbbbbbbbbbbbbbb](https://cloud.githubusercontent.com/assets/14798511/16259978/c40612ca-3897-11e6-8e47-c674500a7542.png)

**Comment by shifujun** [comment]
好吧。这么说吧，模板的bst和大部分Bibtex给出的类型不兼容是学校规范的问题。如果你想帮助模板改进兼容性（我认为不可能完全兼容），你可以读tamethebeast.pdf学习bst文件的撰写方法。
