### ISSUE TITLE
texlive编译，首段文字都没有空两格

### ISSUE THREAD

**Issue by yiranjianning** [shifujun/UESTCthesis#64]
编译环境为texlive2015,windows7,不知为何总是首段文字没有空两格，第二段及以后则正常空两格。用texlive操作的步骤为正常的 pdflatex、Biber、pdflatex和pdflatex。不过用Biber的时候提示出错（模板自带的Template文件夹里的源文件编译也是此步会出错），但是接下来的两步pdflatex都正确结束，且也能正确标明引用等序号。

**Comment by shifujun** [comment]
这个问题是ctex宏包更新后和它的旧版本不兼容造成的。最新版本的模板已经打包了依赖的ctex宏包。需要用模板的编译脚本编译。
