### ISSUE TITLE
Figure

### ISSUE THREAD

**Issue by annalukoko** [shifujun/UESTCthesis#66]
For English, figure caption is in Chinese. Example {figure in chinese} 3.3. How to change so that it Figure or Fig 3.3

**Comment by shifujun** [comment]
see https://github.com/shifujun/UESTCthesis/wiki/english-option-for-international-students
or, search and replace "图" in cls file.
sorry for reply too late.

**Comment by annalukoko** [comment]
Thank you for your response.  You said find and replace but you did not indicate what we should replace it with.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 11, 2017 at 19:44, shifujun<notifications@github.com> wrote:   
see https://github.com/shifujun/UESTCthesis/wiki/english-option-for-international-students
or, search and replace "图" in cls file.
sorry for reply too late.
