### ISSUE TITLE
在ctex_v2.9.2.164和win7 64bit环境下，附件不支持中文？

### ISSUE THREAD

**Issue by wly0218** [shifujun/UESTCthesis#67]
不知道是我的电脑问题还是模版本身的bug，多次测试博士论文模板，我的编译环境为ctex_v2.9.2.164和win7 64bit，英文附件可以很好支持，但附件只要有中文就不支持，请大家一起测试，并请时老师解决，谢谢！

**Comment by shifujun** [comment]
我上班后时间比较紧张，不能花很多时间验证问题。如果要确定这个问题，请不要用ctex来编译了。最新的模板，用texlive套装，2015、2016都可以。要用模板的编译脚本。如果能复现问题，就把一份能复现问题的工作目录打包发上来。

**Comment by wly0218** [comment]
谢谢！texlive套装2016编译成功
