### ISSUE TITLE
问题：中英文摘要后出现空白页

### ISSUE THREAD

**Issue by thesby** [shifujun/UESTCthesis#70]
老师您好！我在win7 上使用texlive 2016 编译模板后，中英文摘要后都出现了一页空白。使用 [wiki](https://github.com/shifujun/UESTCthesis/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9C%89%E4%BA%9B%E7%AB%A0%E6%9C%80%E5%90%8E%E5%A4%9A%E5%87%BA%E4%B8%80%E4%B8%AA%E7%A9%BA%E7%99%BD%E9%A1%B5%EF%BC%9F) 中指导的方法仍然无效。各章节都没有空白，仅摘要部分存在此问题。请问模板本来就是这样吗？我看上一届的师兄论文没有这样的空白页呀？难道是为了打印时避免英文摘要打印到了纸张的反面？

**Comment by shifujun** [comment]
规范要求前置部分都要章起右页的。这是正常的。你可以认为是避免打印到反面的问题。

**Comment by thesby** [comment]
嗯，好的，谢谢您！
