### ISSUE TITLE
怎么让学位论文模板在sharelatex上跑呢

### ISSUE THREAD

**Issue by bruce803** [shifujun/UESTCthesis#73]
时老师，您好。我尝试把论文模板搬到sharelatex或者overleaf上都失败了。因为有时要share给老师们看，他们会直接在线修改。
放到sharelatex上出现这个错误：
dfTeX error: pdflatex (file simsun.ttc): cannot open TrueType font file for reading
==> Fatal error occurred, no output PDF file produced!

**Comment by shifujun** [comment]
失败的直接原因应该是宋体的字体文件simsun.ttc找不到。估计网站是在Linux环境中编译吧。这个字体需要从Windows上获得。wiki上有讲吧。

不过将latex模板弄到网站上去在线编译并不是什么好主意。不使用模板提供的编译脚本，不能保证模板依赖的宏包版本都是正确的，也就不能保证编译效果和预期的一致。这是latex的设计缺陷决定的。

**Comment by wanygen** [comment]
我在overleaf和sharelatex上发布了一个模版试试吧，overleaf在https://www.overleaf.com/latex/templates/uestc-thesis-template/nwpkhtrtjhrg
sharelatex的在https://www.sharelatex.com/templates/58b7c262546799785c1df895

**Comment by bruce803** [comment]
我试试overleaf那个版本吧。请问那个版本跟学校的论文格式要求基本一样吧？

**Comment by wanygen** [comment]
一样的，方正我是找不出什么区别了

**Comment by bruce803** [comment]
good，那就方便多了，多谢。硕士博士没有区别吧？documentclass我改成doctor好像也没啥区别。

**Comment by wanygen** [comment]
本来就没什么区别，页眉换了一下，还有研究成果的标题。

**Comment by evilkjoker** [comment]
mac系统，可以参考[这里](https://tex.stackexchange.com/questions/168732/how-to-install-correctly-simhei-ttf-and-simsun-ttc-for-pdflatex-on-tex-live-2013), 建立目录```/usr/local/texlive/texmf-local```将缺少文件复制进去，然后```mktexlsr ```更新
