### ISSUE TITLE
wiki的图片索引均失效

### ISSUE THREAD

**Issue by FFengIll** [shifujun/UESTCthesis#76]
从我这边观测到的wiki图片索引均已失效。
是否可以将wiki的images资源导入master中引用？
若可以，我将着手完成，并修正image的link。

**Comment by shifujun** [comment]
我刚才看了一下，确实404了。可能是Github有什么规则变动吧。我写的wiki，图片应该都是放在wiki的git目录里的，所以不存在图片丢失的问题。只是以前允许直接引用，现在可能是有什么策略禁止了。

Wiki的编辑权限是所有人都有的，不需要提PR。如果你愿意，可以帮忙整理一下。
建议直接clone https://github.com/shifujun/UESTCthesis.wiki.git 进行编辑。之前的图片也都在里面。

另，另外一个issues里你提到要编辑MikTex的部分。这个稍有点小问题，就这个模板来说，我现在不建议用MikTex了。因为我把依赖的宏包打包到模板里了，就是dependences目录里。然后在编译脚本里指定了依赖的搜索目录。但是这个做法MikTeX不支持。所以我只能推荐大家用TexLive了。MikTeX的总是使用最新宏包的策略其实是有问题的，新版本的宏包并不能保证格式不变，也就不能保证其他人使用模板时和制作的时候设计一致。如果可以，建议帮忙重新编辑一个推荐TeXLive的Wiki.

**Comment by FFengIll** [comment]
链接问题我已经在着手解决，目前已有方案。
我们团队这边今年开始推行使用latex，内部使用的均为Miktex+Texstudio，使用过程中暂时没有发现问题。
关于Miktex的相关问题我会进一步查证后再做补充。

**Comment by FFengIll** [comment]
wiki整理完毕。
